import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { Resend } from "https://esm.sh/resend@2.0.0";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    if (!RESEND_API_KEY) {
      console.error('RESEND_API_KEY is not set');
      throw new Error('Email service not configured. Please add RESEND_API_KEY secret.');
    }

    const resend = new Resend(RESEND_API_KEY);
    const { recipient, subject, body } = await req.json();
    
    if (!recipient || !subject || !body) {
      throw new Error('Missing required fields: recipient, subject, or body');
    }

    console.log('Sending email to:', recipient);

    const emailPayload = {
      from: 'EdgeCrew Demo <demo@justsynq.com>',
      to: [recipient],
      subject: subject,
      html: `
        <html>
          <body>
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
              <h2 style="color: #2ecc71;">Voice Command Email</h2>
              <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
                ${body.replace(/Best regards?/gi, '').replace(/\n/g, '<br>')}
              </div>
              <p style="margin-top: 30px; color: #333;">
                Best Regards,<br>
                EdgeCrew Demo
              </p>
              <p style="color: #666; font-size: 12px; margin-top: 30px;">
                This email was generated by an EdgeCrew voice assistant demo.
              </p>
            </div>
          </body>
        </html>
      `,
    };

    console.log('Attempting to send email');

    const { data, error } = await resend.emails.send(emailPayload);

    if (error) {
      console.error('Resend error details:', JSON.stringify(error));
      
      if (error.message?.includes('domain') || error.message?.includes('verify')) {
        throw new Error('Email domain not verified. Please verify your domain at https://resend.com/domains');
      } else if (error.message?.includes('API key')) {
        throw new Error('Invalid Resend API key. Please check your API key at https://resend.com/api-keys');
      }
      
      throw new Error(`Failed to send email: ${error.message}`);
    }

    console.log('Email sent successfully:', data);

    return new Response(
      JSON.stringify({ 
        message: `Email successfully sent to ${recipient}!`,
        details: {
          recipient,
          subject,
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in send-email:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});
